### ISSUE TITLE
compression-webpack-plugin required on start

### ISSUE THREAD

**Issue by rinu** [frenchrabbit/nuxt-precompress#91]
The `compression-webpack-plugin` dependency should only be required when building a site.

Currently the dependency is also required when running `nuxt-cli start` which doesn't make a lot of sense to me.

The issue currently is in order to use `nuxt-precompress` I have to bundle a bunch of unused code (including all of webpack) with my deployments.

**Comment by maddocnc** [comment]
@rinu Thank you very much for contribution, you are right. Will be published in few hours.
